version: "2"
services:
  flask_restful:
    build: flaskr/
    container_name: flask_restful
    volumes:
      - ./flaskr/:/var/www/
    ports:
      - "3032:3032"
    environment:
      TZ: "Asia/Tokyo"
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - flask_restful
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
